<?php
return array (
  '020001' => 
  array (
    'id' => '020001',
    'name' => '一球成名',
    'short_name' => '',
    'name_py' => 'qw',
    'website' => 'http://yq.demo.ledugame.com/',
    'bbssite' => 'http://bbs.demo.ledugame.com/forum.php',
    'newbie_site' => '',
    'promption_site' => '',
    'loginUrl' => 'http://zqs.yqcm.ledugame.com/ZqRedirectURL.aspx',
    'payUrl' => 'http://zqs.yqcm.ledugame.com/ZqPayment.aspx',
    'checkUserUrl' => 'http://zqs.yqcm.ledugame.com/ZqCheckUser.aspx',
    'template' => 'yqcm',
    'class' => 'YQCM',
    'orderIdPrefix' => 'TESTYQ',
    'star_rating' => '5',
    'game_type' => '2',
    'introduction' => '一球成名》是一款经营策略+RPG类网页游戏',
    'description' => '《一球成名》是一款经营策略+RPG类网页游戏，玩家在游戏中不仅可与上千只球队进行联赛，还可以进入“竞技场”体验PK的快感。游戏中除了以往体育竞技类游戏的模拟养成玩法，更增添了多支球队结成联盟进行“盟战”的设置。还等什么？现在就进入游戏成就自己的足球梦想吧！',
    'image_icon_url' => 'http://kaifu.demo.ledugame.com/upload/yq_t30.gif',
    'image_reconmmend_url' => 'http://kaifu.demo.ledugame.com/upload/pic2.jpg',
    'thumb' => 'http://kaifu.demo.ledugame.com/upload/pic287.jpg',
    'image_list_url' => 'http://kaifu.demo.ledugame.com/upload/yq.jpg',
    'enable_activation' => '0',
    'isPayGame' => '1',
    'pay2where' => '1',
    'key' => 'YQCM::CNTV::KEY(av3dg%hhke2rt)',
    'exchangeRate' => '50',
    'unit' => '金币',
    'status' => '1',
    'sort' => '1',
    'servicearea' => 
    array (
      24 => 
      array (
        'id' => '24',
        'code' => '001',
        'mapcode' => 'ss',
        'name' => 'CNTV一区',
        'status_tag' => '',
        'status' => '0',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => '关服文案七',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      25 => 
      array (
        'id' => '25',
        'code' => '002',
        'mapcode' => '',
        'name' => 'CNTV二区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      26 => 
      array (
        'id' => '26',
        'code' => '003',
        'mapcode' => '',
        'name' => 'CNTV三区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      27 => 
      array (
        'id' => '27',
        'code' => '004',
        'mapcode' => '',
        'name' => 'CNTV四区',
        'status_tag' => '0',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      41 => 
      array (
        'id' => '41',
        'code' => '007',
        'mapcode' => '',
        'name' => '测试服器',
        'status_tag' => '1',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
    ),
  ),
  '020002' => 
  array (
    'id' => '020002',
    'name' => '隋唐名将',
    'short_name' => '',
    'name_py' => 'stmj',
    'website' => 'http://st.demo.ledugame.com/',
    'bbssite' => 'http://bbs.demo.ledugame.com/forum.php',
    'newbie_site' => '',
    'promption_site' => '',
    'loginUrl' => 'http://xb001.sdo.com',
    'payUrl' => 'http://www.ichengzi.com/index.php?controller=data&action=domoney',
    'checkUserUrl' => '',
    'template' => 'stmj',
    'class' => 'STMJ',
    'orderIdPrefix' => 'TESTST',
    'star_rating' => '4',
    'game_type' => '2',
    'introduction' => '《隋唐名将》是一款角色扮演加策略经营类的多人网页游戏。',
    'description' => '《隋唐名将》是根据起点人气武侠小说《大唐行镖》改编的网页游戏，独创走镖护镖式玩法，集角色扮演与经营为一体，融合了横版动作等要素，战斗简洁爽快，向玩家展示了一个集丰富内容与新颖玩法于一身的游戏世界。（如无法进入游戏“<a href="http://get.adobe.com/cn/flashplayer/otherversions/" target="_balnk">点此进入</a>”Adobe Flash Player下载页面）',
    'image_icon_url' => 'http://kaifu.demo.ledugame.com/upload/st_t70.gif',
    'image_reconmmend_url' => 'http://kaifu.demo.ledugame.com/upload/pic4.jpg',
    'thumb' => 'http://kaifu.demo.ledugame.com/upload/pic413.jpg',
    'image_list_url' => 'http://kaifu.demo.ledugame.com/upload/pic474.jpg',
    'enable_activation' => '0',
    'isPayGame' => '1',
    'pay2where' => '1',
    'key' => '9fa0dbf4-be71-11e0-9cf0-277c320c92f7',
    'exchangeRate' => '1',
    'unit' => '通宝',
    'status' => '1',
    'sort' => '2',
    'servicearea' => 
    array (
      28 => 
      array (
        'id' => '28',
        'code' => '001',
        'mapcode' => '',
        'name' => '一区—凌烟阁',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s1.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      29 => 
      array (
        'id' => '29',
        'code' => '001',
        'mapcode' => '',
        'name' => '二区—长生殿',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s1.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      30 => 
      array (
        'id' => '30',
        'code' => '003',
        'mapcode' => '',
        'name' => '三区—观文轩',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s3.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      31 => 
      array (
        'id' => '31',
        'code' => '004',
        'mapcode' => '',
        'name' => '四区—龙虎关',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s4.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => 'zzz',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      32 => 
      array (
        'id' => '32',
        'code' => '005',
        'mapcode' => '',
        'name' => '五区—三义坊',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s5.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => '关服文案七',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      33 => 
      array (
        'id' => '33',
        'code' => '006',
        'mapcode' => '',
        'name' => '测试服器',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://60.28.122.108',
        'ips' => '',
        'offline_tips' => '第一个文案修改',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      39 => 
      array (
        'id' => '39',
        'code' => '002',
        'mapcode' => '',
        'name' => 'qw',
        'status_tag' => '1',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      40 => 
      array (
        'id' => '40',
        'code' => '009',
        'mapcode' => '',
        'name' => 'ert',
        'status_tag' => '1',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
    ),
  ),
  '020003' => 
  array (
    'id' => '020003',
    'name' => '魔道六宗',
    'short_name' => '',
    'name_py' => 'mdlz',
    'website' => 'http://m.ichengzi.com',
    'bbssite' => 'http://bbs.games.ledugame.com/forumdisplay.php?fid=64',
    'newbie_site' => '',
    'promption_site' => '',
    'loginUrl' => '',
    'payUrl' => '',
    'checkUserUrl' => '',
    'template' => 'mdlz',
    'class' => 'MDLZ',
    'orderIdPrefix' => 'TESTMD',
    'star_rating' => '5',
    'game_type' => '2',
    'introduction' => '魔道六宗',
    'description' => '根据起点人气玄幻小说《凡人修仙传》改编的动作角色扮演游戏，首创大气的水墨国画风，利用目前最先进的渲染技术再现了中国国画的古韵美感。游戏画面精美，人物动作流畅，在强大的技术支持下达到了客户端游戏品质，并保留了网页游戏方便快捷、无需安装的优势。',
    'image_icon_url' => 'http://kaifu.demo.ledugame.com/upload/mdlz_t63.gif',
    'image_reconmmend_url' => 'http://kaifu.demo.ledugame.com/upload/mdlz.jpg',
    'thumb' => 'http://kaifu.demo.ledugame.com/upload/mdlz39.jpg',
    'image_list_url' => 'http://kaifu.demo.ledugame.com/upload/mdlz85.jpg',
    'enable_activation' => '0',
    'isPayGame' => '1',
    'pay2where' => '1',
    'key' => 'mdlzkey',
    'exchangeRate' => '0',
    'unit' => '点券',
    'status' => '1',
    'sort' => '5',
    'servicearea' => 
    array (
      34 => 
      array (
        'id' => '34',
        'code' => '001',
        'mapcode' => '',
        'name' => 'CNTV一区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://login.smartgf.com',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      35 => 
      array (
        'id' => '35',
        'code' => '002',
        'mapcode' => '',
        'name' => 'CNTV二区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://login.smartgf.com',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
    ),
  ),
  '020004' => 
  array (
    'id' => '020004',
    'name' => '三国杀',
    'short_name' => '',
    'name_py' => 'sgs',
    'website' => 'http://sgs.ichengzi.com',
    'bbssite' => 'http://bbs.games.ledugame.com/forum.php',
    'newbie_site' => '',
    'promption_site' => '',
    'loginUrl' => 'http://youxi.sanguosha.com/login.php',
    'payUrl' => 'http://youxi.sanguosha.com/order.php',
    'checkUserUrl' => 'http://youxi.sanguosha.com/inquireRole.php',
    'template' => 'sgs',
    'class' => 'SGS',
    'orderIdPrefix' => 'TESTSGS',
    'star_rating' => '4',
    'game_type' => '1',
    'introduction' => '《三国杀OnLine》，聪明人玩的游戏！',
    'description' => '《三国杀OnLine》是热门的桌上游戏《三国杀》Online版，融合了西方类似游戏的特点，并结合中国三国时期背景，以身份为线索，以卡牌为形式，集合历史、文学、美术等元素于一身。',
    'image_icon_url' => 'http://kaifu.demo.ledugame.com/upload/sgs_th91.gif',
    'image_reconmmend_url' => 'http://kaifu.demo.ledugame.com/upload/sgs.jpg',
    'thumb' => 'http://kaifu.demo.ledugame.com/upload/sgs67.jpg',
    'image_list_url' => 'http://kaifu.demo.ledugame.com/upload/sgs41.jpg',
    'enable_activation' => '0',
    'isPayGame' => '1',
    'pay2where' => '1',
    'key' => 'd6252d84ff0cf109d472e2ab0470028a',
    'exchangeRate' => '1',
    'unit' => '点券',
    'status' => '1',
    'sort' => '3',
    'servicearea' => 
    array (
      36 => 
      array (
        'id' => '36',
        'code' => '001',
        'mapcode' => '',
        'name' => 'CNTV专区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 'http://s1.st.ichengzi.com',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
    ),
  ),
  '020005' => 
  array (
    'id' => '020005',
    'name' => '梦回神国',
    'short_name' => '',
    'name_py' => 'mhsg',
    'website' => 'http://mhsg.ichengzi.com',
    'bbssite' => 'http://bbs.games.ledugame.com/forum.php',
    'newbie_site' => '',
    'promption_site' => '',
    'loginUrl' => '',
    'payUrl' => '',
    'checkUserUrl' => '',
    'template' => 'mhsg',
    'class' => 'MHSG',
    'orderIdPrefix' => 'TESTMH',
    'star_rating' => '4',
    'game_type' => '1',
    'introduction' => '极品装备，超高爆率；<br/> 绝世神宠，等你调教！',
    'description' => '《梦回神国》是全球首款采用梦境主题的横版回合制网页游戏，游戏中加入了人物成长系统，让您可以在虚拟世界里体验真实的生老病死。游戏采用以宠物战斗为主体，人物角色辅助攻击的模式，游戏中宠物系统丰富，不仅战宠种类众多，还拥有特别宠物养成功能，还可以工作、进化等。',
    'image_icon_url' => 'http://kaifu.demo.ledugame.com/upload/mhsg_tx67.gif',
    'image_reconmmend_url' => 'http://kaifu.demo.ledugame.com/upload/mhsg.jpg',
    'thumb' => 'http://kaifu.demo.ledugame.com/upload/mhsg18.jpg',
    'image_list_url' => 'http://kaifu.demo.ledugame.com/upload/mhsg20.jpg',
    'enable_activation' => '0',
    'isPayGame' => '1',
    'pay2where' => '1',
    'key' => 'w5sa415sldmtp94aq2616937sq8d3vn6',
    'exchangeRate' => '10',
    'unit' => '元宝',
    'status' => '1',
    'sort' => '4',
    'servicearea' => 
    array (
      37 => 
      array (
        'id' => '37',
        'code' => '001',
        'mapcode' => '',
        'name' => 'CNTV一区',
        'status_tag' => '',
        'status' => '',
        'loginUrl' => 's1.mhsg.ichengzi.com',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
      38 => 
      array (
        'id' => '38',
        'code' => '002',
        'mapcode' => '',
        'name' => '123123',
        'status_tag' => '1',
        'status' => '',
        'loginUrl' => '',
        'ips' => '',
        'offline_tips' => '',
        'showPrefix' => '',
        'showSuffix' => '',
      ),
    ),
  ),
);

